# Generated by Django 6.0.5 on 2026-06-03 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0004_documentchunk_vector_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("project", "Project"),
                            ("company", "Company"),
                            ("technology", "Technology"),
                            ("topic", "Topic"),
                            ("concept", "Concept"),
                            ("other", "Other"),
                        ],
                        default="topic",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_documents",
                    models.ManyToManyField(
                        blank=True, related_name="entities", to="documents.document"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "unique_together": {("owner", "title", "node_type")},
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("works_on", "Works On"),
                            ("uses", "Uses"),
                            ("belongs_to", "Belongs To"),
                            ("references", "References"),
                            ("related_to", "Related To"),
                        ],
                        default="related_to",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("weight", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_edges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="graph.node",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="graph.node",
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "source", "target", "relationship_type")},
            },
        ),
    ]
