# Generated by Django 5.0.6 on 2026-07-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_documentchunk_vector_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentchunk",
            old_name="content",
            new_name="text",
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="page_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="char_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="token_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="document",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
