# Generated by Django 6.0.5 on 2026-07-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0005_rename_content_documentchunk_text_document_file_size_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("txt", "Text"),
                    ("docx", "DOCX"),
                    ("md", "Markdown"),
                    ("image", "Image"),
                    ("link", "Link"),
                    ("note", "Note"),
                ],
                max_length=20,
            ),
        ),
    ]
