# Generated by Django 6.0.5 on 2026-07-24 16:03

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_file_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='doc_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
