# Generated by Django 6.0.5 on 2026-07-24 16:03

from django.db import migrations


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_file_type_and_more'),
    ]

    operations = [
        # HnswIndex is postgres-only; skip on SQLite.
        migrations.RunPython(noop, noop),
    ]
