# Generated by Django 6.0.5 on 2026-08-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_documentchunk_doc_chunk_embedding_hnsw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]